# Generated by Django 4.2.9 on 2024-02-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reply_comment_tred_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='started_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='started_by',
            new_name='created_by',
        ),
    ]
