# Generated by Django 4.2.9 on 2024-02-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_author_name_alter_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
