# Generated by Django 4.2.9 on 2024-02-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
    ]
