# Generated by Django 4.2.9 on 2024-02-02 08:38

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[100, 100], upload_to='avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default=None, max_length=150, unique=True, verbose_name='Псевдоним'),
        ),
    ]
