# Generated by Django 4.2.9 on 2024-02-02 17:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_author_avatar_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[250, 250], upload_to='tred_images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='reply',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[250, 250], upload_to='tred_images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='tred',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[250, 250], upload_to='tred_images', verbose_name='Изображение'),
        ),
    ]
